/* CREATE ENTITIES TABLE
# RESET AUTO_INCREMENT TO 0 */

CREATE TABLE `ENTITIES` (
  `ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_NAME` varchar(55) DEFAULT NULL,
  `WIKI_URL` varchar(255) DEFAULT NULL,
  `WIKI_IMAGE_URL` text DEFAULT NULL,
  PRIMARY KEY (`ENTITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;