/* REDEPLOY DATABASE */

/* Drop the tables in DEV */
USE DEV;
DROP TABLE ENTITIES;
DROP TABLE TWEETS;

/* Drop the tables in PROD */
USE PROD;
DROP TABLE ENTITIES;
DROP TABLE TWEETS;

/* Drop the databases */
DROP DATABASE DEV;
DROP DATABASE PROD;

/* Recreate the databases */
CREATE DATABASE DEV;
CREATE DATABASE PROD;

/* Recreate the tables in Dev */
USE DEV;

CREATE TABLE `ENTITIES` (
  `ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_NAME` varchar(55) DEFAULT NULL,
  `WIKI_URL` varchar(255) DEFAULT NULL,
  `WIKI_IMAGE_URL` text DEFAULT NULL,
  PRIMARY KEY (`ENTITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


CREATE TABLE `TWEETS` (
  `UNIQUE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TWITTER_ID` varchar(55) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`UNIQUE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

/* Recreate the tables in Prod */
USE PROD;

CREATE TABLE `ENTITIES` (
  `ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_NAME` varchar(55) DEFAULT NULL,
  `WIKI_URL` varchar(255) DEFAULT NULL,
  `WIKI_IMAGE_URL` text DEFAULT NULL,
  PRIMARY KEY (`ENTITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


CREATE TABLE `TWEETS` (
  `UNIQUE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TWITTER_ID` varchar(55) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`UNIQUE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;