/* CREATES THE TWEETS TABLE
RESETS THE AUTO INCREMENT TO 0 */

CREATE TABLE `TWEETS` (
  `UNIQUE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TWITTER_ID` varchar(55) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`UNIQUE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;