apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nimbus
  name: nimbus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nimbus
    spec:
      containers:
      - args:
        - storm
        - nimbus
        image: gcr.io/big-data-energy/nimbus
        name: nimbus
        ports:
        - containerPort: 6627
        resources: {}
      restartPolicy: Always
status: {}
