apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: supervisor
  name: supervisor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: supervisor
    spec:
      containers:
      - args:
        - storm
        - supervisor
        image: gcr.io/big-data-energy/supervisor
        name: supervisor
        resources: {}
      restartPolicy: Always
status: {}
